-- =====================================================================
--  PozosPharma — Herbal & Traditional Medicine Seed (h1–h18)
-- =====================================================================
--  ⚠️  AI-DRAFTED CONTENT — NOT VERIFIED BY A PHARMACIST OR HERBAL AUTHORITY  ⚠️
--
--  Common Ghanaian / West African herbs. Drafted from ethnobotanical and
--  pharmacology literature. Every row has reviewed_by = NULL.
--
--  KEY PRINCIPLE: `evidence_level` states how well a use is actually supported —
--  "traditional use only" means popular use WITHOUT reliable clinical proof.
--  The app must show evidence_level and herb_drug_interactions prominently and
--  must NOT present traditional use as medical fact. Herbal ≠ safe: several of
--  these have real toxicity and drug interactions (see safety_concerns).
--
--  Apply with:
--    wrangler d1 execute pozospharma-db --file=herbs-seed.sql
-- =====================================================================

INSERT OR IGNORE INTO herbs
  (id, common_name, local_names, scientific_name, traditional_uses, evidence_level, active_constituents, herb_drug_interactions, safety_concerns, pregnancy_caution, preparation, source_reference, source_url, reviewed_by, reviewed_at)
VALUES
  ('h1','Moringa','Zangala, Yevu-ti / "miracle tree"','Moringa oleifera','Nutritional supplement, "blood tonic", blood pressure and blood sugar support, breastmilk stimulation','limited clinical evidence','Vitamins A/C, iron, quercetin, isothiocyanates','May add to the effect of antidiabetic drugs (hypoglycemia) and antihypertensives; theoretical thyroid interaction','Leaf is generally well tolerated; root/bark contain spirochin and should be avoided; quality/adulteration of powders varies','Leaf is considered safe in food amounts; avoid concentrated root/bark preparations in pregnancy','Fresh or dried leaf as food, tea, or powder','Ethnobotanical & pharmacology literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h2','Neem','Dua gyene, Dogonyaro','Azadirachta indica','Malaria, fever, skin conditions, worms, antiseptic wash','traditional use only','Azadirachtin, nimbin, limonoids','May add to hypoglycemic drugs; may oppose immunosuppressants; caution with hepatotoxic drugs','Neem oil/seed can be hepatotoxic and cause encephalopathy in infants (do NOT give neem oil to babies); overdose toxicity','Avoid in pregnancy — reported abortifacient and anti-fertility effects','Leaf decoction, oil (topical); seed extracts','Ethnobotanical & pharmacology literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h3','Prekese (Aidan fruit)','Prekese, Aridan','Tetrapleura tetraptera','Soup spice, postpartum care, blood pressure, blood sugar, "cleansing"','traditional use only','Saponins, flavonoids, aridanin','Theoretical additive effect with antihypertensives and antidiabetics','Generally food-safe as a spice; concentrated extracts not well studied','Widely used postpartum in tradition, but concentrated medicinal doses are not well studied — use caution','Pod boiled in soups/decoction','Ethnobotanical literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h4','Cryptolepis (Nibima)','Nibima, Ghana quinine','Cryptolepis sanguinolenta','Uncomplicated malaria, fever, infections (a well-known Ghanaian antimalarial herb; basis of some registered phytomedicines)','moderate evidence','Cryptolepine (indoloquinoline alkaloid)','May add to blood-pressure-lowering drugs; theoretical additive QT/cardiac effect with antimalarials and QT-prolonging drugs','Not for severe/complicated malaria (needs hospital treatment); alkaloid may affect heart rhythm and blood pressure at high doses','Avoid in pregnancy — insufficient safety data and alkaloid content','Root decoction; standardised phytomedicine products','Ghanaian antimalarial ethnopharmacology (AI-drafted — pending expert review)','',NULL,NULL),
  ('h5','Bitter leaf','Awonwono, Ewuro','Vernonia amygdalina','Diabetes, malaria, fever, appetite, "cleansing"','limited clinical evidence','Vernonioside, sesquiterpene lactones','May add to antidiabetic drugs (hypoglycemia) and antihypertensives','Very bitter; large amounts may cause GI upset; hypoglycemia if combined with diabetes medicines','Avoid strong medicinal decoctions in pregnancy (limited data; possible uterine effects)','Leaf decoction (washed to reduce bitterness), soup','Ethnobotanical & pharmacology literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h6','Hibiscus (Sobolo / Bissap)','Sobolo, Bissap, Roselle','Hibiscus sabdariffa','Refreshing drink, blood pressure lowering, "cooling"','moderate evidence','Anthocyanins, organic acids','Adds to antihypertensive drugs (may lower BP further); studies suggest it can REDUCE plasma levels/absorption of chloroquine and diclofenac — separate dosing','Generally safe as a drink; very high intake may affect the liver; heavily sweetened sobolo adds sugar','Avoid large medicinal amounts in pregnancy (possible effects on the uterus/hormones)','Calyces steeped/boiled as a drink','Clinical & pharmacokinetic literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h7','Ginger','Akakaduro','Zingiber officinale','Nausea, cold and cough, digestion, pain','moderate evidence','Gingerols, shogaols','Antiplatelet effect — increased bleeding risk with warfarin, aspirin, clopidogrel; may add to antidiabetic/antihypertensive drugs','Generally safe in food amounts; heartburn at high doses; bleeding risk mainly with high medicinal doses plus blood thinners','Food amounts considered acceptable; avoid high medicinal doses near delivery/with bleeding risk','Fresh root tea, food, extract','Pharmacology literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h8','Garlic','Galik','Allium sativum','Blood pressure, cholesterol, infections, immune support','moderate evidence','Allicin, ajoene, organosulfur compounds','Induces drug metabolism — can REDUCE levels of some HIV protease inhibitors (e.g., saquinavir) and ciclosporin; antiplatelet — bleeding risk with warfarin/aspirin','Safe as food; medicinal/supplement doses carry bleeding and drug-interaction risks','Food amounts fine; avoid high-dose supplements peri-operatively and with anticoagulants','Raw/cooked clove, aged extract, capsules','Pharmacology & HIV pharmacotherapy literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h9','Aloe vera','Aloe','Aloe vera / Aloe barbadensis','Topical for burns/skin; oral juice for constipation and "cleansing"','limited clinical evidence','Aloin (latex), polysaccharides (gel)','Oral latex is a stimulant laxative — causes potassium loss that can worsen digoxin toxicity and interact with diuretics/antiarrhythmics; may reduce absorption of oral drugs','Topical gel is generally safe; oral latex can cause cramps, diarrhea, electrolyte loss, and is not for long-term use','Avoid oral aloe (latex) in pregnancy — stimulant laxative/uterine effects','Gel applied to skin; juice/latex taken orally (discouraged)','Pharmacology literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h10','Guava leaf','Guava, Gova','Psidium guajava','Diarrhea, wounds, mouth ulcers, blood sugar','limited clinical evidence','Quercetin, tannins, flavonoids','May add to antidiabetic drugs (hypoglycemia); tannins may reduce absorption of iron and some drugs','Generally well tolerated; constipation with very high tannin intake','Limited data in pregnancy — use food/mild amounts only','Leaf decoction/tea; chewed young leaves','Ethnobotanical & pharmacology literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h11','Bitter kola','Bese, Namijin goro','Garcinia kola','Cough, chest and throat infections, aphrodisiac, "energy"','traditional use only','Kolaviron (biflavonoids)','Limited interaction data; theoretical additive effect with drugs affecting the liver','Generally chewed; high intake effects not well characterised; product quality varies','Insufficient safety data in pregnancy — avoid medicinal amounts','Seed chewed raw; decoction','Ethnobotanical literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h12','Kola nut','Bese, Goro','Cola nitida / Cola acuminata','Stimulant, fatigue, appetite suppression, social/ceremonial use','moderate evidence','Caffeine, theobromine','Adds to other stimulants and caffeine; may raise blood pressure and heart rate; theoretical interaction with some antidepressants (MAOIs)','Contains caffeine — palpitations, insomnia, raised BP with heavy use; dependence','Limit caffeine in pregnancy (as with coffee)','Seed chewed; powder','Pharmacology literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h13','Lemongrass (Fever grass)','Ntadware, Ti-tea','Cymbopogon citratus','Fever, malaria adjunct, colds, digestion, calming tea','traditional use only','Citral, geraniol','Theoretical additive with sedatives and antihypertensives; limited data','Generally safe as a tea; very high doses not studied','Food/tea amounts generally acceptable; avoid strong medicinal decoctions in pregnancy','Leaf infusion/tea','Ethnobotanical literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h14','Turmeric','Turmeric, Ginger-family','Curcuma longa','Anti-inflammatory, joint pain, digestion, wound care','moderate evidence','Curcumin','Antiplatelet/anticoagulant effect — bleeding risk with warfarin/aspirin; may raise levels of some drugs (P-glycoprotein); can reduce iron absorption','Safe as a spice; high-dose supplements carry bleeding and interaction risks; some products adulterated','Food amounts fine; avoid high-dose supplements in pregnancy','Powder in food; extract/capsule','Pharmacology literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h15','Pawpaw (Papaya) leaf','Borɔferɛ, Pawpaw','Carica papaya','Malaria/fever, low platelets (dengue belief), deworming, digestion','traditional use only','Carpaine, papain, flavonoids','Theoretical additive with anticoagulants; limited data','Leaf latex can irritate; unproven for raising platelets — do not rely on it in serious illness','Avoid in pregnancy — unripe fruit/latex are traditionally abortifacient','Leaf juice/decoction','Ethnobotanical literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h16','Baobab','Kuka, Adansonia fruit','Adansonia digitata','Fruit drink (vitamin C), fever, diarrhea, "immune boost"','limited clinical evidence','Vitamin C, pectin, antioxidants','Few known interactions; high fibre may slightly affect drug absorption','Generally food-safe; very high fibre may cause bloating','Food amounts considered safe','Fruit pulp drink; leaf','Ethnobotanical & nutrition literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h17','Shea butter','Nkuto, Kpakahili','Vitellaria paradoxa','Topical for skin, hair, minor wounds, massage','limited clinical evidence','Fatty acids, tocopherols, triterpenes','None significant (topical use)','Topical use is generally very safe; nut allergy is rare','Topical use considered safe in pregnancy','Applied to skin/hair','Ethnobotanical literature (AI-drafted — pending expert review)','',NULL,NULL),
  ('h18','Griffonia (African 5-HTP)','Kagya, Gyama','Griffonia simplicifolia','Mood, sleep, appetite control (a natural 5-HTP source)','limited clinical evidence','5-Hydroxytryptophan (5-HTP)','SERIOUS: risk of serotonin syndrome if combined with SSRIs/SNRIs, tramadol, MAOIs, or triptans; adds to sedatives','Provides 5-HTP — can cause nausea and, combined with serotonergic drugs, dangerous serotonin excess','Avoid in pregnancy — insufficient safety data and serotonergic activity','Seed extract/capsule; decoction','Pharmacology literature (AI-drafted — pending expert review)','',NULL,NULL);
